### ISSUE TITLE
Old django version support

### ISSUE THREAD

**Issue by sshishov** [Polyconseil/django-cid#47]
Just a question. Why did you drop support of old Django versions and old python versions.
A lot of big projects are still using these versions as it is quite difficult for them to migrate.
We would like to use your library in our projects but all projects have different setup, some of them are python3.7 and latest Django and some of them are python2.7 and Django1.7.

If we add support only for a half of out setup then it just does not make any sense. Just curiosity why it is difficult to support old versions?!

**Comment by dbaty** [comment]
Hi. django-cid is indeed small enough that supporting old versions would not be a huge burden. However, it's still a burden. :)

If we support Django 1.7, why not supporting Django 1.3 as well? If we support Python 2.7, why not 2.4 too? How old is too old? Somehow, we must draw a line somewhere. We hence try to follow [Django official timeline of supported versions](https://www.djangoproject.com/download/#supported-versions), which I think is quite conservative already.

You mention Django 1.7: the official extended support ended almost 4 years ago (2015-12-01). You may have reasons to still use this ancient version, but you can hardly ask support for it.

I am torn on Python 2.7. It is usable with Django 1.11, which is still supported (as an LTS) until April 2020. On the other hand, let's face it: Python 2 is a thing of the past.

I am not disparaging your use of old versions of Python and Django. We (Polyconseil) have been there as well, lagging behind. I don't think everyone can or wants to be bleeding-edge, but they must know what it entails. (We're still not bleeding-edge and are still migrating some code from Django 2.1 to 2.2.)

If one needs compatibility with an old version of Python and/or Django, they can always use an old version of django-cid. Obviously, they won't have access to the newest features or bug fixes, but that's what comes with using old versions.
