### ISSUE TITLE
Add Django 3.0 support

### ISSUE THREAD

**Issue by tonial** [Polyconseil/django-cid#52]
Hello, 

Django 3.0 is now available.
The only two changes with this release that seems to affect django-cid are :
- dropping the `django.db.backends.postgresql_psycopg2.base` alias to `django.db.backends.postgresql.base`.
- Django 3.0 is only tested against python 3.6+

Also, Django release notes suggest to drop support for Django version prior to 2.2.

With all that in mind, I've made this PR (#51) that :
- stop testing with Django 2.1
- stop using the old alias
- Test with Django 3.0 and python 3.6-3.8

We don't need to change the requirement for Django>=1.11 `django.db.backends.postgresql_psycopg2.base` was already an alias to `django.db.backends.postgresql.base` in Django 1.11.

**Comment by dbaty** [comment]
The corresponding pull request (#51) has been merged.
