### ISSUE TITLE
contextvars isn't used

### ISSUE THREAD

**Issue by wicol** [Polyconseil/django-cid#60]
Hey!

I think there is a typo here (`get_gid` should be `get_cid`):
https://github.com/Polyconseil/django-cid/blob/595f64a51a71bd4a1d47eefdb56002d72629d603/cid/locals/__init__.py#L4

It results in an ImportError and the fallback to thread_local is always used:
```
Python 3.9.13 (main, May 29 2022, 04:54:28)
...
>>> from cid.locals import get_cid
>>> get_cid.__module__
'cid.locals.thread_local'
```

**Comment by dbaty** [comment]
Ouch, that's embarrassing... Good catch!

I introduced this bug in c3a3b8a8adda6eb6321917c2f2dbad401f75ee80. I'll fix it and cut a new release. Thanks for the report.
