### ISSUE TITLE
Generate a CID if one was not included in the request

### ISSUE THREAD

**Issue by emnoor** [Polyconseil/django-cid#64]
Hello. I would like to make a feature request.

I want to only generate a new correlation id if it is missing in the request; but use the one if one is passed in the request. If you are OK with it, I will put something together and send a pull request.

**Comment by dbaty** [comment]
Hi. If I understand correctly, this feature is already available. For this you'll have to:

- enable a middleware: `cid.middleware.CidMiddleware`;
- override `CID_HEADER` in your settings if the default value (`X_CORRELATION_ID`) does not suit you.

For further details (and an important "gotcha" about setting `CID_HEADER` when behing a WSGI server), see https://django-correlation-id.readthedocs.io/en/latest/installation.html#generation-of-the-correlation-id. We'll gladly accept suggestions if you think that the documentation is not clear.

**Comment by emnoor** [comment]
Ah, I see. I got confused by this section:

> The correlation id may be generated by `django-cid` itself or come from upstream through an incoming HTTP header.
>
> To let `django-cid` generate an id, set `CID_GENERATE` to true in the settings:

I think it could be framed like this to avoid confusion:

> The correlation id may be generated by `django-cid` itself or come from upstream through an incoming HTTP header.
>
> If correlation id is not preset in the upstream, `django-cid` can optionally generate it. To let `django-cid` generate an id, set `CID_GENERATE` to true in the settings:
