### ISSUE TITLE
Proposal: use logging.makeRecordFactory

### ISSUE THREAD

**Issue by dzen** [Polyconseil/django-cid#9]
Hello,

I think it would be safer to create a RecordFactory to initialise the record with a cid attribute, to avoid KeyError on some logging occasions.
https://docs.python.org/2/library/logging.html#logging.Logger.makeRecord

Exemple:

``` python

old_factory = logging.getLogRecordFactory()
def cid_record_factory(*args, **kwargs):
    record = old_factory(*args, **kwargs)
    record.cid = None
    return record

logging.makeRecordFactory(cid_record_factory)
```

**Comment by dbaty** [comment]
As discussed with Benoît, I am closing this issue because it is not relevant anymore.
